update the arg to new Makefile logic
raspbernetes/multi-arch-images pull request #145
Opened 2020-08-29 01:21 UTC by xUnholy

Signed-off-by: Michael Fornaro <20387402+xUnholy@users.noreply.github.com>

# Description

Testing logic to fix csi-external-provisioner to allow for new Makefile logic in upstream

## Type Of Change

To help us figure out who should review this PR, please put an X in all the areas that this PR affects.

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] Test and/or Release
- [ ] User Experience

## Issue Ref (Optional)

Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged): Fixes #144 

## Notes

Add special notes for your reviewer here.

2020-08-29 12:00 UTC, Trackhe requested changes
in build/csi-external-provisioner/Dockerfile line 3 needs an Update.
However i test it and it is not working too.

2020-08-29 12:07 UTC, Trackhe commented
The Problem is now also for csi-attacher and longhorn-csi-plugin

2020-09-02 08:15 UTC, xUnholy commented
@Trackhe it will be all the updates to this particular version as the upstream has changed their main implementation, I saw locally that it didn't respect the `GOOS` & `GOARCH` values we provided previously so we'd need to update that logic in the Dockerfile to work with the new Makefile logic. Feel free to try as I won't be able to address this any time soon unfortunately.

2020-09-02 16:17 UTC, d7volker commented
This is working for me, but I need this for a couple other images, too.
Please let me know if you require some help.

2020-09-14 09:49 UTC, xUnholy commented
Fixed in https://github.com/raspbernetes/multi-arch-images/pull/154

2020-09-14 09:49 UTC, closed without merging